[package]
name = "lobot"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
tauri = { version = "1.2", features = ["dialog-all", "fs-create-dir", "fs-read-dir", "fs-remove-file", "path-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
llm-chain-local = '0.9.1'
llm-chain-llama = "0.9.3"
llm-chain-openai = "0.8.2"
llm-chain = "0.10.1"
tokio = { version = "1", features = ["full"] }
anyhow = '1.0'
thiserror = '1.0.40'

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
