version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'

  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'
    ignore:
      # Ignore updates to packages that start with 'aws'
      # Wildcards match zero or more arbitrary characters
      - dependency-name: 'llm'
      # Ignore some updates to the 'express' package
      - dependency-name: 'llm-chain'
