version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'
    ignore:
      # ignore all patch updates
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'
    ignore:
      - dependency-name: 'llm'
      - dependency-name: 'llm-chain'
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
