root: true
parser: '@typescript-eslint/parser'
extends:
  [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:svelte/recommended'
  ]
env: { es6: true, browser: true }
parserOptions:
  { sourceType: 'module', ecmaVersion: 2020, extraFileExtensions: ['.svelte'] }
overrides:
  [
    {
      files: ['*.svelte'],
      parser: 'svelte-eslint-parser',
      parserOptions: { parser: '@typescript-eslint/parser' }
    }
  ]
plugins: ['@typescript-eslint']
