parser: '@typescript-eslint/parser'
extends:
  [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'plugin:svelte/recommended'
  ]
env: { es6: true, browser: true }
parserOptions: { project: './tsconfig.json', extraFileExtensions: ['.svelte'] }
overrides:
  [
    {
      files: ['*.svelte'],
      parser: 'svelte-eslint-parser',
      parserOptions: { parser: '@typescript-eslint/parser' }
    }
  ]
plugins: ['@typescript-eslint']
