singleQuote: true
bracketSpacing: true
semi: false
tabWidth: 2
trailingComma: 'none'
plugins: ['prettier-plugin-svelte']
svelteSortOrder: 'options-styles-scripts-markup'
svelteStrictMode: true
svelteBracketNewLine: false
svelteAllowShorthand: false
svelteIndentScriptAndStyle: false
